spring.application.name=DesafioBancario

spring.datasource.url=jdbc:mysql://localhost:3306/API_Desafio_Picpay
spring.datasource.username=root
spring.datasource.password=juninho7

spring.jpa.hibernate.ddl-auto=create
